# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

updateEta_c <- function(Lambda, ps, k, Y, n) {
    .Call(`_SBIFM_updateEta_c`, Lambda, ps, k, Y, n)
}

updateLambda_c <- function(eta, Plam, ps, Y, k, p) {
    .Call(`_SBIFM_updateLambda_c`, eta, Plam, ps, Y, k, p)
}

updatePsi_c <- function(df, Lambda, tauh, p, k) {
    .Call(`_SBIFM_updatePsi_c`, df, Lambda, tauh, p, k)
}

updateDeltaTauh_c <- function(Lambda, psijh, ad1, p, k, bd1, delta, tauh, ad2, bd2) {
    .Call(`_SBIFM_updateDeltaTauh_c`, Lambda, psijh, ad1, p, k, bd1, delta, tauh, ad2, bd2)
}

updateSigma_c <- function(tmp2, p, as, n, bs) {
    .Call(`_SBIFM_updateSigma_c`, tmp2, p, as, n, bs)
}

